apiVersion: v1
kind: Pod
metadata:
  name: copier
  namespace: airflow
spec:
  containers:
    - name: copier
      image: alpine:3.19
      command:
        - sh
        - -c
        - |
          # Install rsync
          apk add --no-cache rsync

          while true; do
            # Copy file differences from a PV into an ephemeral volume
            # Remove files at target which are not present at the source anymore
            rsync -a --delete /opt/airflow/dags/ /tmp/dags/
            sleep 60
          done
      volumeMounts:
        - name: tmp-dags
          mountPath: /tmp/dags
        - name: dags
          mountPath: /opt/airflow/dags
  volumes:
    # Temporary volume for code pulled by git-sync
    - name: tmp-dags
      emptyDir: {}
    # Azure File Share PV where code will be saved and can be mounted to other pods
    - name: dags
      persistentVolumeClaim:
        claimName: airflow-dags-pvc
``