# This is a deployment running git-sync which pulls code from a repo and saves it in a persistent volume which is then mounted into Airflow pods

apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: git-sync
  template:
    metadata:
      labels:
        app: git-sync
    spec:
      # Init container for setting permissions to the folder where we will be cloning repo
      # 65533 is UID of the user used in the image
      initContainers:
        - name: init-repo
          image: busybox
          command: ["sh", "-c", "mkdir -p /opt/airflow/dags && chown -R 65533:65533 /opt/airflow/dags"]
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.6.0
          env:
            - name: GIT_SYNC_REPO
              value: {{ .Values.gitSync.repoURL }}
            - name: GIT_SYNC_BRANCH
              value: {{ .Values.gitSync.branch }}
            - name: GIT_SYNC_ROOT
              value: {{ .Values.gitSync.clonePath }}
            - name: GIT_SYNC_WAIT
              value: "60"   # sync interval in seconds
          volumeMounts:
            - name: dags 
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc