# Add to the Service Account used by the Airflow scheduler permissions for creating pods (since we use KubernetesExecutor, each Airflow task will run
# in its own, new pod).

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: airflow
  name: airflow-pod-manager
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - events
    verbs:
      - create
      - get
      - list
      - watch
      - delete
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-pod-manager-binding
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: airflow
roleRef:
  kind: ClusterRole
  name: airflow-pod-manager
  apiGroup: rbac.authorization.k8s.io
